apiVersion: v1
kind: ConfigMap
metadata:
  name: my-settings
data:
  APP_VERSION: "2.0"
  ENV: "asia-staging" 
  ENV_TYPE: "non-prod" 
  REGION: "asia" 
  PAYPAL_URL: "staging2.paypal.com"     
  DB_USER: "non-prod-user" 
  DB_PASSWORD: "non-prod-password" 
  GPU_ENABLED: "0" 
  UI_THEME: "light" 
  CACHE_SIZE: "4096kb" 
  PAGE_LIMIT: "50" 
  SORTING: "ascending" 
  N_BUCKETS: "42"   


